# Copyright Â© 2024 ANSYS, Inc. Unauthorized use, distribution, or duplication is prohibited.
[build-system]
requires = ["setuptools >= 80.9.0", "wheel", "ansys_tools_protoc_helper"]
build-backend = "setuptools.build_meta:__legacy__"