# Copyright Â© 2024 ANSYS, Inc. Unauthorized use, distribution, or duplication is prohibited.
[build-system]
requires = [
  "setuptools >= 80.9.0",
  "wheel",
  "protobuf==4.21.12",
  "grpcio-tools<1.64.0",
  "ansys-tools-protoc-helper"
]
build-backend = "setuptools.build_meta:__legacy__"