# Copyright Â© 2024 ANSYS, Inc. Unauthorized use, distribution, or duplication is prohibited.
[build-system]
requires = ["setuptools >= 42.0.0", "wheel", "ansys_tools_protoc_helper>=0.5.0"]
build-backend = "setuptools.build_meta:__legacy__"
